[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[naiados-repo]
SigLevel = Optional TrustAll
Server = file:///root/naiados-repo
