title   NaiadOS (%ARCH%, UEFI)
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-naiados-lts
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-naiados-lts.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID%